name: Build, Test, and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            main_cmd: g++ main.cpp -std=c++17 -o build/polyglot -Wno-ignored-attributes
            test_cmd: g++ test_runner.cpp -std=c++17 -o build/test-runner
          - os: macos-latest  
            main_cmd: clang++ main.cpp -std=c++17 -o build/polyglot -Wno-ignored-attributes
            test_cmd: clang++ test_runner.cpp -std=c++17 -o build/test-runner
          - os: windows-latest
            main_cmd: g++ main.cpp -std=c++17 -o build/polyglot.exe -Wno-ignored-attributes
            test_cmd: g++ test_runner.cpp -std=c++17 -o build/test-runner.exe
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y python3-pyflakes
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Use pipx or install via Homebrew if available
        brew install pyflakes || pipx install pyflakes || python3 -m pip install --user pyflakes
    
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pip install pyflakes
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Build main project
      run: ${{ matrix.main_cmd }}
    
    - name: Build test runner
      run: ${{ matrix.test_cmd }}
    
    - name: Make binaries executable (Unix)
      if: matrix.os != 'windows-latest'
      run: chmod +x build/polyglot build/test-runner
    
    - name: Make binaries executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        if exist build\polyglot.exe echo "Windows executable built"
        if exist build\test-runner.exe echo "Test runner built"
    
    - name: Run tests from project root
      run: |
        cd "$GITHUB_WORKSPACE"
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ./build/test-runner.exe
        else
          ./build/test-runner
        fi
    
    - name: Upload main binaries as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: polyglot-${{ matrix.os }}
        path: build/polyglot*
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: build/polyglot*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}