name: Build Project

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            make_cmd: g++ main.cpp -std=c++17 -o polyglot
          - os: macos-latest  
            make_cmd: clang++ main.cpp -std=c++17 -o polyglot
          - os: windows-latest
            make_cmd: g++ main.cpp -std=c++17 -o polyglot
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build project
      run: ${{ matrix.make_cmd }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: polyglot-${{ matrix.os }}
        path: ./